#!/usr/bin/env bash
# Starlink exit-node — VPS-side WireGuard + policy-routing setup (Phase 1).
#
# WHAT THIS DOES (additive only — nothing existing is modified or restarted):
#   1. Installs wireguard-tools if missing.
#   2. Generates a NEW keypair for this VPS's wg-starlink0 interface (private
#      key never leaves this box; not committed to git).
#   3. Writes /etc/wireguard/wg-starlink0.conf — a NEW interface, listening on
#      a dedicated UDP port, with ONE peer slot for the Starlink gateway
#      (public key filled in later, once the gateway generates its own).
#   4. Adds a DEDICATED routing table (id 90) + `ip rule` that only matches
#      traffic sourced from the tunnel's internal VPS-side address
#      (10.90.0.1) — nothing else on this box is affected. SSH, the database,
#      monitoring, and every other outbound keep using the main table.
#   5. Prints (does NOT apply) the Xray outbound + routing-rule JSON snippet
#      to add to the existing Xray config.json by hand, so you can review the
#      diff before restarting Xray. Xray is NOT touched or restarted by this
#      script.
#
# WHAT THIS DOES NOT DO:
#   - Does not modify any existing Xray inbound/outbound/routing entry.
#   - Does not modify the main routing table.
#   - Does not open any port other than the one WireGuard UDP listener.
#   - Does not restart nginx, xray, or any other service.
#
# Run this on the VPS that will host the Starlink WireGuard listener (review
# with Khabat first — see docs/STARLINK_NODE_ARCHITECTURE.md §9 step 3).

set -euo pipefail

WG_IFACE="wg-starlink0"
WG_PORT="${STARLINK_WG_PORT:-51900}"
WG_VPS_ADDR="10.90.0.1/30"
WG_PEER_ADDR="10.90.0.2/32"
RT_TABLE_ID=90
RT_TABLE_NAME="starlink"

echo "== Starlink VPS-side WireGuard setup =="
echo "Interface: $WG_IFACE  Port: $WG_PORT  VPS tunnel IP: $WG_VPS_ADDR"
echo

if ! command -v wg >/dev/null 2>&1; then
  echo "-- Installing wireguard-tools --"
  apt-get update -qq && apt-get install -y -qq wireguard-tools
fi

WG_DIR="/etc/wireguard"
mkdir -p "$WG_DIR"
chmod 700 "$WG_DIR"

if [[ ! -f "$WG_DIR/$WG_IFACE.key" ]]; then
  echo "-- Generating new WireGuard keypair (private key stays in $WG_DIR, chmod 600) --"
  umask 077
  wg genkey | tee "$WG_DIR/$WG_IFACE.key" | wg pubkey > "$WG_DIR/$WG_IFACE.pub"
fi
PRIVATE_KEY="$(cat "$WG_DIR/$WG_IFACE.key")"
PUBLIC_KEY="$(cat "$WG_DIR/$WG_IFACE.pub")"

echo
echo "== VPS public key (give this to the Starlink gateway setup script) =="
echo "$PUBLIC_KEY"
echo

if [[ ! -f "$WG_DIR/$WG_IFACE.conf" ]]; then
  cat > "$WG_DIR/$WG_IFACE.conf" <<EOF
# Starlink node: starlink-no-01 — generated by setup-starlink-wg.sh
# This interface ONLY carries Starlink-exit traffic (policy-routed by source
# IP below). It does not become the box's default route for anything.
[Interface]
Address = $WG_VPS_ADDR
ListenPort = $WG_PORT
PrivateKey = $PRIVATE_KEY
# No PostUp/PostDown NAT here — this box is the WG "server" side; NAT/egress
# happens on the STARLINK side (deploy/starlink/gateway/), not here.

[Peer]
# Starlink gateway device. PublicKey is filled in once the gateway generates
# its own keypair (deploy/starlink/gateway/setup-*.sh prints it).
# No fixed Endpoint = the gateway is behind CGNAT and roams; WireGuard learns
# its current source address/port from the latest valid handshake and keeps
# the NAT mapping open via the gateway's PersistentKeepalive.
PublicKey = <PASTE_GATEWAY_PUBLIC_KEY_HERE>
AllowedIPs = $WG_PEER_ADDR
EOF
  chmod 600 "$WG_DIR/$WG_IFACE.conf"
  echo "-- Wrote $WG_DIR/$WG_IFACE.conf (placeholder peer key — edit before starting) --"
else
  echo "-- $WG_DIR/$WG_IFACE.conf already exists, leaving it alone --"
fi

echo
echo "-- Dedicated routing table (id $RT_TABLE_ID, name '$RT_TABLE_NAME') --"
if ! grep -q "^$RT_TABLE_ID $RT_TABLE_NAME\$" /etc/iproute2/rt_tables 2>/dev/null; then
  echo "$RT_TABLE_ID $RT_TABLE_NAME" >> /etc/iproute2/rt_tables
  echo "   added to /etc/iproute2/rt_tables"
else
  echo "   already present"
fi

cat <<'EOF'

-- Policy routing rule (apply AFTER wg-starlink0 is up) --
Run these once the interface is up (they do NOT persist across reboot on
their own — add them to the wg-starlink0.conf [Interface] PostUp/PostDown,
shown below, once you've confirmed they work):

  ip rule add from 10.90.0.1 table starlink
  ip route add default dev wg-starlink0 table starlink

To make this persistent, add to the [Interface] section of
/etc/wireguard/wg-starlink0.conf:

  PostUp   = ip rule add from 10.90.0.1 table starlink; ip route add default dev wg-starlink0 table starlink
  PostDown = ip rule del from 10.90.0.1 table starlink; ip route del default dev wg-starlink0 table starlink

This ONLY affects traffic sourced from 10.90.0.1 — the address the new Xray
"starlink-exit" outbound binds to via sendThrough (see the Xray snippet
below). Nothing else changes route.

EOF

echo "-- Firewall: open the WireGuard UDP port (least privilege — one port, no other change) --"
if command -v ufw >/dev/null 2>&1; then
  echo "   ufw allow $WG_PORT/udp comment 'starlink-wg'"
else
  echo "   iptables -A INPUT -p udp --dport $WG_PORT -j ACCEPT   # adjust to this box's actual firewall tool"
fi

echo
echo "== Xray config change (REVIEW, then apply by hand — Xray is not restarted by this script) =="
cat <<'JSON'
Add ONE new outbound to the existing Xray config.json "outbounds" array
(after "direct" and "block" — do not remove or reorder the existing ones):

  {
    "tag": "starlink-exit",
    "protocol": "freedom",
    "settings": { "domainStrategy": "AsIs" },
    "sendThrough": "10.90.0.1"
  }

Add ONE new routing rule to the existing "routing.rules" array, matching ONLY
the dedicated per-node Starlink test UUID (from the admin panel's
"starlink-update-node" action / admin/index.php Starlink tab) — place it
BEFORE the catch-all/default rules so it takes precedence for that one user:

  {
    "type": "field",
    "user": ["<STARLINK_TEST_UUID_HERE>"],
    "outboundTag": "starlink-exit"
  }

Every other client keeps matching the existing rules and using "direct" —
this new rule only ever matches the one dedicated Starlink-test UUID.

After editing config.json:
  xray -test -config /usr/local/etc/xray/config.json   # validate BEFORE restart
  systemctl restart xray                                 # only after -test passes
JSON

echo
echo "== Done. Next: run the matching gateway script on the Starlink-side device, =="
echo "== paste its public key into $WG_DIR/$WG_IFACE.conf, then: =="
echo "==   systemctl enable --now wg-quick@$WG_IFACE =="
