# Resolve react_native_pods.rb via node (RN 0.73+ pattern)
require Pod::Executable.execute_command('node', ['-e',
  "process.stdout.write(require('path').dirname(require.resolve('react-native/package.json')))",
  '--no-warnings'
]).strip + '/scripts/react_native_pods.rb'

platform :ios, min_ios_version_supported
prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'Realink' do
  config = use_native_modules!

  use_react_native!(
    path:           config[:reactNativePath],
    hermes_enabled: true,
    app_path:       "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false
    )
  end
end
