#!/usr/bin/env bash
# ReaLink VPS Helper — installs a LOCAL-ONLY outbound proxy on a VPS so that
# tools running ON the VPS (e.g. Claude Code / the Anthropic API) reach the
# internet through a ReaLink exit node (Finland/Germany) instead of the VPS's
# own — often censored or sanctioned — IP.
#
# WHY THIS EXISTS
#   A phone VPN only tunnels the PHONE. When a user SSHes into their VPS with
#   Termius and runs Claude there, that traffic originates ON THE VPS and never
#   touches the phone — so no phone-side per-app bypass can fix it, and Anthropic
#   blocks Iranian IPs regardless. The fix must live on the VPS. This helper is
#   that fix, packaged so nobody has to hand-roll xray.
#
# SAFETY / NON-GOALS (by design)
#   * The proxy binds ONLY to 127.0.0.1 (SOCKS + HTTP). Never publicly exposed.
#   * It is an APPLICATION proxy (opt-in via HTTPS_PROXY / SOCKS). It installs
#     NO TUN device, NO iptables/nftables redirect, NO global proxy. Your
#     inbound SSH/Termius session and all other VPS traffic are untouched.
#   * Only processes that you point at it (export HTTPS_PROXY=...) use the exit
#     node. Everything else — including sshd — keeps its normal path.
#   * Fully reversible: `--uninstall` removes it; the node-side identity is
#     revoked separately by the operator (see provision.sh --revoke).
#
# USAGE
#   Install:    curl -fsSL https://setalink.no/download/vps-helper | REALINK_PROFILE='<base64>' bash
#   or:         REALINK_PROFILE='<base64>' bash realink-vps-helper.sh
#   or:         bash realink-vps-helper.sh --profile '<base64>'
#   Status:     bash realink-vps-helper.sh --status
#   Verify:     bash realink-vps-helper.sh --verify
#   Uninstall:  bash realink-vps-helper.sh --uninstall
#
# The <base64> profile is generated by the operator with provision.sh and carries
# this VPS's dedicated node credentials (UUID + Reality params). It is a bearer
# secret — treat the install command like a password; revoke if leaked.
set -euo pipefail

DIR=/usr/local/realink-vps-helper
SVC=realink-vps-helper
BIN="$DIR/xray"
CFG="$DIR/config.json"
ENVF="$DIR/proxy.env"
XRAY_LATEST="https://github.com/XTLS/Xray-core/releases/latest/download"

log()  { printf '\033[36m[realink]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[realink WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m[realink ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

need_root() { [ "$(id -u)" = 0 ] || die "run as root (sudo). Installs a systemd service."; }

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64)          echo "Xray-linux-64.zip" ;;
    aarch64|arm64)         echo "Xray-linux-arm64-v8a.zip" ;;
    armv7l|armv7|armhf)    echo "Xray-linux-arm32-v7a.zip" ;;
    *) die "unsupported arch '$(uname -m)' — supported: x86_64, arm64, armv7" ;;
  esac
}

install_deps() {
  local miss=()
  command -v curl  >/dev/null 2>&1 || miss+=(curl)
  command -v unzip >/dev/null 2>&1 || miss+=(unzip)
  [ "${#miss[@]}" -eq 0 ] && return 0
  log "installing dependencies: ${miss[*]}"
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y -qq "${miss[@]}"
  elif command -v dnf >/dev/null 2>&1; then dnf install -y -q "${miss[@]}"
  elif command -v yum >/dev/null 2>&1; then yum install -y -q "${miss[@]}"
  elif command -v apk >/dev/null 2>&1; then apk add --no-cache "${miss[@]}"
  else die "could not auto-install ${miss[*]} — please install them and retry"; fi
}

load_profile() {
  local b64="${REALINK_PROFILE:-${1:-}}"
  [ -n "$b64" ] || die "no profile. Pass REALINK_PROFILE=<base64> or --profile <base64>."
  local tmp; tmp="$(mktemp)"
  printf '%s' "$b64" | base64 -d > "$tmp" 2>/dev/null || die "profile is not valid base64"
  # profile is a sourceable KEY=VALUE env file (no JSON parser needed on the VPS)
  # shellcheck disable=SC1090
  . "$tmp"; rm -f "$tmp"
  : "${RVH_UUID:?profile missing RVH_UUID}"
  : "${RVH_ADDRESS:?}" "${RVH_PORT:?}" "${RVH_PBK:?}" "${RVH_SID:?}" "${RVH_SNI:?}"
  RVH_FLOW="${RVH_FLOW:-}"; RVH_FP="${RVH_FP:-chrome}"
  RVH_SOCKS="${RVH_SOCKS:-10808}"; RVH_HTTP="${RVH_HTTP:-10809}"
  RVH_EXIT="${RVH_EXIT:-}"; RVH_TAG="${RVH_TAG:-vpsh}"; RVH_NODE="${RVH_NODE:-node}"
}

download_xray() {
  [ -x "$BIN" ] && { log "xray already present, keeping it"; return 0; }
  local asset; asset="$(detect_arch)"
  log "downloading xray-core ($asset)"
  local tmp; tmp="$(mktemp -d)"
  curl -fsSL "$XRAY_LATEST/$asset" -o "$tmp/x.zip" || die "xray download failed"
  unzip -oq "$tmp/x.zip" -d "$tmp" || die "unzip failed"
  install -Dm755 "$tmp/xray" "$BIN"
  # geo data enables the geoip:private→direct safety rule
  [ -f "$tmp/geoip.dat" ]   && install -Dm644 "$tmp/geoip.dat"   "$DIR/geoip.dat"   || true
  [ -f "$tmp/geosite.dat" ] && install -Dm644 "$tmp/geosite.dat" "$DIR/geosite.dat" || true
  rm -rf "$tmp"
  "$BIN" version 2>/dev/null | head -1 || warn "xray version check produced no output"
}

write_config() {
  log "writing client config (SOCKS 127.0.0.1:$RVH_SOCKS · HTTP 127.0.0.1:$RVH_HTTP → $RVH_NODE)"
  # flow is only valid when non-empty (Germany node uses flow=""); build users obj accordingly
  local user_flow=""
  [ -n "$RVH_FLOW" ] && user_flow=",\"flow\":\"$RVH_FLOW\""
  mkdir -p "$DIR"
  cat > "$CFG" <<EOF
{
  "log": { "loglevel": "warning" },
  "inbounds": [
    { "tag": "socks", "listen": "127.0.0.1", "port": $RVH_SOCKS,
      "protocol": "socks", "settings": { "udp": true, "auth": "noauth" } },
    { "tag": "http", "listen": "127.0.0.1", "port": $RVH_HTTP,
      "protocol": "http", "settings": {} }
  ],
  "outbounds": [
    { "tag": "proxy", "protocol": "vless",
      "settings": { "vnext": [ { "address": "$RVH_ADDRESS", "port": $RVH_PORT,
        "users": [ { "id": "$RVH_UUID", "encryption": "none"$user_flow } ] } ] },
      "streamSettings": { "network": "tcp", "security": "reality",
        "realitySettings": { "serverName": "$RVH_SNI", "fingerprint": "$RVH_FP",
          "publicKey": "$RVH_PBK", "shortId": "$RVH_SID", "spiderX": "" } } },
    { "tag": "direct", "protocol": "freedom" },
    { "tag": "block", "protocol": "blackhole" }
  ],
  "routing": { "domainStrategy": "AsIs",
    "rules": [ { "type": "field", "ip": [ "geoip:private" ], "outboundTag": "direct" } ] }
}
EOF
  XRAY_LOCATION_ASSET="$DIR" "$BIN" run -test -c "$CFG" >/dev/null 2>&1 \
    || die "generated xray config failed validation"
}

write_env() {
  cat > "$ENVF" <<EOF
# Source this (or copy the lines) in the shell where you run Claude / your tools.
# Only these processes will exit via the ReaLink node ($RVH_NODE); everything
# else on the VPS — including your SSH session — is unaffected.
export HTTPS_PROXY=http://127.0.0.1:$RVH_HTTP
export HTTP_PROXY=http://127.0.0.1:$RVH_HTTP
export https_proxy=http://127.0.0.1:$RVH_HTTP
export http_proxy=http://127.0.0.1:$RVH_HTTP
# Keep localhost/VPS-internal calls direct:
export NO_PROXY=localhost,127.0.0.1,::1
export no_proxy=localhost,127.0.0.1,::1
EOF
}

write_service() {
  cat > "/etc/systemd/system/$SVC.service" <<EOF
[Unit]
Description=ReaLink VPS Helper (local-only outbound proxy via ReaLink node)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=XRAY_LOCATION_ASSET=$DIR
ExecStart=$BIN run -c $CFG
Restart=on-failure
RestartSec=5
# hardening: no privileged ports needed, loopback-only listeners
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=$DIR
ProtectHome=true

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable "$SVC" >/dev/null 2>&1 || true
  systemctl restart "$SVC"
  sleep 2
  systemctl is-active --quiet "$SVC" || die "service failed to start (journalctl -u $SVC)"
}

verify() {
  local hp="${RVH_HTTP:-10809}" ip=""
  log "verifying exit IP through the proxy…"
  for _ in 1 2 3; do
    ip="$(curl -x "http://127.0.0.1:$hp" -m 12 -fsS https://api.ipify.org 2>/dev/null || true)"
    [ -n "$ip" ] && break; sleep 2
  done
  [ -n "$ip" ] || { warn "could not fetch exit IP through proxy yet (node reachable from this VPS?)"; return 1; }
  log "exit IP via proxy: $ip"
  if [ -n "${RVH_EXIT:-}" ] && [ "$ip" = "$RVH_EXIT" ]; then
    log "MATCH — traffic exits via the ReaLink $RVH_NODE node ($RVH_EXIT). ✅"
  elif [ -n "${RVH_EXIT:-}" ]; then
    warn "exit IP $ip != expected node IP $RVH_EXIT (still non-VPS — check node egress)"
  fi
  # reachability probe to Anthropic (any HTTP status = reachable through Finland)
  local code
  code="$(curl -x "http://127.0.0.1:$hp" -m 12 -s -o /dev/null -w '%{http_code}' https://api.anthropic.com/v1/models 2>/dev/null || echo 000)"
  [ "$code" != "000" ] && log "api.anthropic.com reachable through proxy (HTTP $code)" \
                        || warn "api.anthropic.com not reachable through proxy (HTTP 000)"
  return 0
}

do_install() {
  need_root; install_deps; load_profile "${1:-}"; download_xray
  write_config; write_env; write_service; verify || true
  cat <<EOF

$(printf '\033[32m✔ ReaLink VPS Helper installed and running.\033[0m')

To make Claude (and any tool) exit via the ReaLink $RVH_NODE node, run this in
the shell where you start it — or add it to your Claude launch:

  source $ENVF
  claude          # now reaches api.anthropic.com via $RVH_NODE ($RVH_EXIT)

Your SSH/Termius session and everything else on the VPS are UNCHANGED.
Uninstall any time:  bash $0 --uninstall
EOF
}

do_uninstall() {
  need_root
  log "stopping and removing ReaLink VPS Helper"
  systemctl disable --now "$SVC" >/dev/null 2>&1 || true
  rm -f "/etc/systemd/system/$SVC.service"; systemctl daemon-reload || true
  rm -rf "$DIR"
  log "removed. NOTE: ask the operator to REVOKE this VPS's node UUID (provision.sh --revoke)."
}

do_status() {
  systemctl status "$SVC" --no-pager 2>/dev/null | head -6 || echo "not installed"
  [ -f "$ENVF" ] && { echo; echo "proxy env: $ENVF"; }
}

case "${1:-}" in
  --uninstall) do_uninstall ;;
  --status)    do_status ;;
  --verify)    load_profile ""; verify ;;
  --profile)   do_install "${2:-}" ;;
  -h|--help)   sed -n '2,40p' "$0" ;;
  *)           do_install "" ;;
esac
