// AUTO-GENERATED by scripts/release.sh (Android) or ios-testflight.yml (iOS).
// Mirrors android/app/build.gradle versionName/versionCode so the JS bundle
// always reports the build it was actually compiled into. Keeping this in sync
// with the native build is what stops the OTA checker from offering an update
// that is already installed.
export const APP_VERSION    = '0.9.68';
export const APP_BUILD      = '95';
export const APP_BUILD_CODE = 95;
