// AUTO-GENERATED by scripts/release.sh — do not edit by hand.
// Mirrors android/app/build.gradle versionName/versionCode so the JS bundle
// always reports the build it was actually compiled into. Keeping this in sync
// with the native build is what stops the OTA checker from offering an update
// that is already installed.
export const APP_VERSION    = '0.9.106';
export const APP_BUILD      = '146';
export const APP_BUILD_CODE = 146;
