// Diagnostics report builder (BUG-3, Issue 2). Pure/serializable so it can be
// unit-tested and reused by the share-sheet / copy-to-clipboard actions on the
// Diagnostics screen. No PII beyond the device's own ID is included, and the
// caller decides where the text goes (share intent, clipboard, file).

import type { HealthCheck, RouteHop, ConnectionInfo } from './diagnosticsEngine';

export interface DiagnosticsReportInput {
  appVersion:   string;
  appBuild:     string;
  deviceId:     string;
  platform:     string;        // e.g. 'android'
  osVersion:    string | number;
  tunnelStatus: string;        // connectionState
  exitIp:       string | null;
  dnsStatus:    string;        // 'Healthy' | 'Degraded' | 'Failed' | 'Unknown'
  healthChecks: HealthCheck[];
  routeHops:    RouteHop[];
  connection?:  ConnectionInfo | null;
  timestamp?:   number;        // defaults to now
}

const STATUS_LABEL: Record<string, string> = { ok: 'Healthy', warn: 'Degraded', fail: 'Failed' };

/** Build a human-readable, shareable diagnostic report. Always returns a string. */
export function buildDiagnosticsReport(i: DiagnosticsReportInput): string {
  const ts = new Date(i.timestamp ?? Date.now()).toISOString();
  const L: string[] = [];
  L.push('SetaLink Diagnostic Report');
  L.push('==========================');
  L.push(`Timestamp:     ${ts}`);
  L.push(`App version:   ${i.appVersion} (build ${i.appBuild})`);
  L.push(`Device ID:     ${i.deviceId || 'unknown'}`);
  L.push(`Platform:      ${i.platform} ${i.osVersion}`);
  L.push(`Tunnel status: ${i.tunnelStatus}`);
  L.push(`Exit IP:       ${i.exitIp || '—'}`);
  L.push(`DNS status:    ${i.dnsStatus}`);

  if (i.connection) {
    L.push('');
    L.push('Protocol');
    L.push('--------');
    L.push(`  Protocol:    ${i.connection.protocol}`);
    L.push(`  Transport:   ${i.connection.transport}`);
    L.push(`  Server SNI:  ${i.connection.serverSni}`);
    L.push(`  TLS:         ${i.connection.tlsVersion} · ${i.connection.cipher}`);
  }

  L.push('');
  L.push('Health Checks');
  L.push('-------------');
  for (const h of i.healthChecks) {
    L.push(`  [${(STATUS_LABEL[h.status] ?? h.status).toUpperCase()}] ${h.label} — ${h.detail}`);
  }

  L.push('');
  L.push('Route Trace');
  L.push('-----------');
  for (const r of i.routeHops) {
    L.push(`  ${r.hop}. ${r.ip.padEnd(16)} ${String(r.rtt).padEnd(6)} ${r.label}`);
  }

  L.push('');
  L.push('— Generated by SetaLink VPN');
  return L.join('\n');
}
