// Diagnostics report builder (BUG-3, Issue 2). Pure/serializable so it can be
// unit-tested and reused by the share-sheet / copy-to-clipboard actions on the
// Diagnostics screen. No PII beyond the device's own ID is included, and the
// caller decides where the text goes (share intent, clipboard, file).
//
// 2026-07-02: the illustrative Health Checks and fake Route Trace sections were
// removed — simulated values in exported reports repeatedly derailed real
// debugging sessions. The report now carries ONLY live measurements: the Self
// Test results (real probes through the tunnel) and the VPN-verified exit IP.

import type { ConnectionInfo } from './diagnosticsEngine';
import type { SelfTestResult } from './vpnBridge';

export interface DiagnosticsReportInput {
  appVersion:   string;
  appBuild:     string;
  deviceId:     string;
  platform:     string;        // e.g. 'android'
  osVersion:    string | number;
  tunnelStatus: string;        // connectionState
  exitIp:       string | null; // VPN-verified only (trace test), never direct-network
  dnsStatus:    string;        // 'Healthy' | 'Degraded' | 'Failed' | 'Unknown'
  selfTest?:    SelfTestResult[] | null;  // live probe results from the Self Test tab
  connection?:  ConnectionInfo | null;
  timestamp?:   number;        // defaults to now
}

/** Build a human-readable, shareable diagnostic report. Always returns a string. */
export function buildDiagnosticsReport(i: DiagnosticsReportInput): string {
  const ts = new Date(i.timestamp ?? Date.now()).toISOString();
  const L: string[] = [];
  L.push('Realink Diagnostic Report');
  L.push('==========================');
  L.push(`Timestamp:     ${ts}`);
  L.push(`App version:   ${i.appVersion} (build ${i.appBuild})`);
  L.push(`Device ID:     ${i.deviceId || 'unknown'}`);
  L.push(`Platform:      ${i.platform} ${i.osVersion}`);
  L.push(`Tunnel status: ${i.tunnelStatus}`);
  // Exit IP is only valid when the tunnel is connected and a trace test confirmed
  // the route. Never filled from a direct-network IP fetch.
  L.push(`Exit IP:       ${i.exitIp || (i.tunnelStatus === 'connected' ? '(run internet test to detect)' : 'N/A — tunnel not connected')}`);
  L.push(`DNS status:    ${i.tunnelStatus === 'connected' ? i.dnsStatus : 'Unknown (tunnel not connected)'}`);

  if (i.connection) {
    L.push('');
    L.push('Protocol');
    L.push('--------');
    L.push(`  Protocol:    ${i.connection.protocol}`);
    L.push(`  Transport:   ${i.connection.transport}`);
    L.push(`  Server SNI:  ${i.connection.serverSni}`);
    L.push(`  TLS:         ${i.connection.tlsVersion} · ${i.connection.cipher}`);
  }

  L.push('');
  L.push('Self Test (live probes through the tunnel)');
  L.push('-------------------------------------------');
  const st = i.selfTest ?? [];
  if (st.length === 0) {
    L.push('  (not run — open the Self Test tab and run it before exporting');
    L.push('   so this report carries real measurements)');
  } else {
    for (const r of st) {
      L.push(`  [${r.ok ? 'PASS' : 'FAIL'}] ${r.label}${r.detail ? ` — ${r.detail}` : ''}`);
    }
  }

  L.push('');
  L.push('— Generated by Realink VPN');
  return L.join('\n');
}
