<?php
/**
 * Generate the xray Recovery-Mode inbound + routing config from the single-source
 * allowlist in lib/ads_recovery.php (ar_allowlist). This is a DEPLOY ARTIFACT
 * GENERATOR — it prints JSON to stdout; it does NOT touch any live server.
 *
 * Recovery Mode is a DEDICATED inbound with GLOBAL routing: every device on it
 * gets the same SNI/DNS allowlist + throttle, so no per-user distinction is needed
 * (the live tunnel can't tell mobile devices apart — see docs §1).
 *
 * Usage:
 *   php scripts/gen-recovery-xray.php > /tmp/recovery-inbound.json
 *   # review, then merge the inbound + routing rules into the recovery node's
 *   # xray config and reload. Set the recovery_exit_* settings to match.
 *
 * Args (optional): --port=443 --uuid=... --pbk=... --sid=... --sni=www.cloudflare.com
 *                  --throttle-kbps=512
 */

require_once __DIR__ . '/../lib/ads_recovery.php';

$opt = getopt('', ['port::', 'uuid::', 'pbk::', 'sid::', 'sni::', 'throttle-kbps::']);
$port     = (int)($opt['port'] ?? 443);
$uuid     = $opt['uuid'] ?? 'REPLACE_WITH_RECOVERY_UUID';
$pbk      = $opt['pbk']  ?? 'REPLACE_WITH_REALITY_PRIVATE_KEY';
$sid      = $opt['sid']  ?? 'REPLACE_WITH_SHORT_ID';
$sni      = $opt['sni']  ?? 'www.cloudflare.com';
$throttle = (int)($opt['throttle-kbps'] ?? 512);

$allow = ar_allowlist();
// xray domain matchers: "domain:apex" matches the apex and all subdomains.
$allowDomains = array_map(fn($d) => 'domain:' . $d, $allow);

$config = [
    '_comment' => 'Realink Recovery-Mode inbound — GLOBAL allowlist + throttle. '
                . 'Generated by scripts/gen-recovery-xray.php from ar_allowlist(). '
                . 'NOT auto-deployed. throttle ' . $throttle . ' kbps.',
    'inbounds' => [[
        'tag'      => 'recovery-in',
        'listen'   => '0.0.0.0',
        'port'     => $port,
        'protocol' => 'vless',
        'settings' => [
            'clients'    => [[ 'id' => $uuid, 'flow' => 'xtls-rprx-vision' ]],
            'decryption' => 'none',
        ],
        'streamSettings' => [
            'network'  => 'tcp',
            'security' => 'reality',
            'realitySettings' => [
                'show'        => false,
                'dest'        => $sni . ':443',
                'serverNames' => [$sni],
                'privateKey'  => $pbk,
                'shortIds'    => [$sid],
            ],
        ],
        // Sniffing extracts the real SNI/domain so routing can allowlist by domain
        // WITHOUT decrypting user payload (compliant).
        'sniffing' => [ 'enabled' => true, 'destOverride' => ['tls', 'http', 'quic'], 'routeOnly' => true ],
    ]],
    'outbounds' => [
        [ 'tag' => 'allow-out', 'protocol' => 'freedom' ],
        [ 'tag' => 'block-out', 'protocol' => 'blackhole' ],
    ],
    'routing' => [
        'domainStrategy' => 'AsIs',
        'rules' => [
            // 1) Allowlisted essential domains → out.
            [ 'type' => 'field', 'inboundTag' => ['recovery-in'], 'domain' => $allowDomains, 'outboundTag' => 'allow-out' ],
            // 2) Everything else on the recovery inbound → blackhole (no free internet).
            [ 'type' => 'field', 'inboundTag' => ['recovery-in'], 'outboundTag' => 'block-out' ],
        ],
    ],
    '_throttle_note' => "Bandwidth throttle ({$throttle} kbps) is not an xray-core primitive. "
        . 'Enforce via tc/HTB on the recovery node NIC for this inbound port, or run the recovery '
        . 'inbound behind a rate-limited nginx/HAProxy stream. The app also honours profile.throttle_kbps.',
];

echo json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
