#!/usr/bin/env bash
# scripts/release.sh — build and publish a new SetaLink Android release
#
# Usage:
#   ./scripts/release.sh [--channel stable|beta|hotfix] [--version X.Y.Z]
#
# Examples:
#   ./scripts/release.sh                          # bump patch, stable channel
#   ./scripts/release.sh --version 0.9.11         # explicit version
#   ./scripts/release.sh --channel beta            # beta channel
#   ./scripts/release.sh --channel hotfix --version 0.9.10.1

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$REPO_ROOT/mobile-app"
PACKAGE_JSON="$APP_DIR/package.json"
BUILD_GRADLE="$APP_DIR/android/app/build.gradle"
RELEASES_DIR="$REPO_ROOT/public/releases"
DOWNLOAD_DIR="$REPO_ROOT/public/download"
VERSION_JSON="$DOWNLOAD_DIR/version.json"

CHANNEL="stable"
EXPLICIT_VERSION=""
PUBLISH_ONLY=0
APK_DIR=""

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --channel)       CHANNEL="$2";          shift 2 ;;
    --version)       EXPLICIT_VERSION="$2"; shift 2 ;;
    # --publish-only: skip the version bump and the on-box Gradle build, and
    #   publish APKs that were already built elsewhere (GitHub Actions). The
    #   1 GB VPS cannot run a RN release build — see android/gradle.properties.
    --publish-only)  PUBLISH_ONLY=1;        shift   ;;
    # --apk-dir DIR: directory holding the CI-built app-*-release.apk files.
    #   Defaults to the local Gradle output dir when omitted.
    --apk-dir)       APK_DIR="$2";          shift 2 ;;
    *)               echo "Unknown arg: $1"; exit 1  ;;
  esac
done

if [[ ! "$CHANNEL" =~ ^(stable|beta|hotfix)$ ]]; then
  echo "ERROR: --channel must be stable, beta, or hotfix"
  exit 1
fi

# ── Determine version ─────────────────────────────────────────────────────────
CURRENT_VERSION=$(node -pe "require('$PACKAGE_JSON').version" 2>/dev/null)

if [[ "$PUBLISH_ONLY" -eq 1 ]]; then
  # Publish-only: the version files were already bumped (by a prior run of this
  # script or by hand) and the APKs were built in CI. Read the current values
  # straight from the source of truth — do NOT bump again.
  NEW_VERSION="$CURRENT_VERSION"
  NEW_CODE=$(grep -oP 'versionCode\s+\K\d+' "$BUILD_GRADLE")
  echo "==> Publish-only: v$NEW_VERSION (versionCode $NEW_CODE) [$CHANNEL]"
else
  if [[ -n "$EXPLICIT_VERSION" ]]; then
    NEW_VERSION="$EXPLICIT_VERSION"
  else
    # Auto-bump patch component
    IFS='.' read -r MAJOR MINOR PATCH <<< "${CURRENT_VERSION//-*/}"
    PATCH=$((PATCH + 1))
    NEW_VERSION="$MAJOR.$MINOR.$PATCH"
  fi

  # Bump versionCode: read current, increment by 1
  CURRENT_CODE=$(grep -oP 'versionCode\s+\K\d+' "$BUILD_GRADLE")
  NEW_CODE=$((CURRENT_CODE + 1))

  echo "==> Release: $CURRENT_VERSION → $NEW_VERSION (versionCode $NEW_CODE) [$CHANNEL]"

  # ── Update version files ────────────────────────────────────────────────────
  # package.json
  cd "$APP_DIR" && npm version "$NEW_VERSION" --no-git-tag-version --allow-same-version
  echo "    package.json updated"

  # build.gradle
  sed -i "s/versionCode\s\+[0-9]\+/versionCode    $NEW_CODE/" "$BUILD_GRADLE"
  sed -i "s/versionName\s\+\".*\"/versionName    \"$NEW_VERSION\"/" "$BUILD_GRADLE"
  echo "    build.gradle updated"

  # version.ts — single source of truth for the JS bundle, generated from the
  # native build so APP_VERSION/APP_BUILD can never drift from the installed APK.
  VERSION_TS="$APP_DIR/src/utils/version.ts"
  cat > "$VERSION_TS" << EOF
// AUTO-GENERATED by scripts/release.sh — do not edit by hand.
// Mirrors android/app/build.gradle versionName/versionCode so the JS bundle
// always reports the build it was actually compiled into. Keeping this in sync
// with the native build is what stops the OTA checker from offering an update
// that is already installed.
export const APP_VERSION    = '$NEW_VERSION';
export const APP_BUILD      = '$NEW_CODE';
export const APP_BUILD_CODE = $NEW_CODE;
EOF
  echo "    version.ts regenerated ($NEW_VERSION / $NEW_CODE)"
fi

# ── Build APK ─────────────────────────────────────────────────────────────────
if [[ "$PUBLISH_ONLY" -eq 1 ]]; then
  echo "==> Skipping build (--publish-only); using prebuilt APKs"
else
  echo "==> Building APK..."
  cd "$APP_DIR/android"
  ./gradlew assembleRelease --no-daemon -q
  echo "    Build complete"
fi

# ── Locate built APKs ─────────────────────────────────────────────────────────
# --apk-dir wins when given (CI artifacts); otherwise use the Gradle output dir.
APK_OUT="${APK_DIR:-$APP_DIR/android/app/build/outputs/apk/release}"
APK_SRC="$APK_OUT/app-arm64-v8a-release.apk"
APK_SRC_ARM32="$APK_OUT/app-armeabi-v7a-release.apk"
APK_SRC_UNIVERSAL="$APK_OUT/app-universal-release.apk"
CHANNEL_DIR="$RELEASES_DIR/$CHANNEL"
APK_NAME="setalink-v${NEW_VERSION}.apk"
APK_NAME_ARM32="setalink-v${NEW_VERSION}-arm32.apk"
APK_NAME_UNIVERSAL="setalink-v${NEW_VERSION}-universal.apk"
APK_DEST="$CHANNEL_DIR/$APK_NAME"

# Fail fast with a clear message if any expected APK is missing (common in
# --publish-only when --apk-dir points at the wrong place or CI didn't finish).
for f in "$APK_SRC" "$APK_SRC_ARM32" "$APK_SRC_UNIVERSAL"; do
  if [[ ! -f "$f" ]]; then
    echo "ERROR: expected APK not found: $f" >&2
    echo "       (looked in APK_OUT=$APK_OUT — pass --apk-dir to override)" >&2
    exit 1
  fi
done

# Reclaim ownership from a previous run's final www-data chown (see below)
# so this run's cp/rm calls succeed as the ubuntu user — without this,
# every run after the first fails here since the prior run's own chown left
# these dirs write-only for www-data (ubuntu isn't in that group).
sudo chown -R ubuntu:ubuntu "$RELEASES_DIR" "$REPO_ROOT/public/assets" "$DOWNLOAD_DIR" 2>/dev/null || true

mkdir -p "$CHANNEL_DIR"
cp "$APK_SRC" "$APK_DEST"
ln -sf "$APK_NAME" "$CHANNEL_DIR/setalink-latest.apk"
echo "    APK (arm64) → $APK_DEST"

# 32-bit compat APK (Samsung J/A series and other armeabi-v7a-only devices)
# and universal APK (both ABIs, for users who can't determine their ABI).
cp "$APK_SRC_ARM32" "$CHANNEL_DIR/$APK_NAME_ARM32"
ln -sf "$APK_NAME_ARM32" "$CHANNEL_DIR/setalink-latest-arm32.apk"
echo "    APK (arm32 compat) → $CHANNEL_DIR/$APK_NAME_ARM32"

cp "$APK_SRC_UNIVERSAL" "$CHANNEL_DIR/$APK_NAME_UNIVERSAL"
ln -sf "$APK_NAME_UNIVERSAL" "$CHANNEL_DIR/setalink-latest-universal.apk"
echo "    APK (universal) → $CHANNEL_DIR/$APK_NAME_UNIVERSAL"

# Also update assets/ compatibility path and latest symlinks
cp "$APK_DEST" "$REPO_ROOT/public/assets/$APK_NAME"
ln -sf "../releases/$CHANNEL/$APK_NAME" "$DOWNLOAD_DIR/setalink-latest.apk"
ln -sf "../releases/$CHANNEL/$APK_NAME_ARM32" "$DOWNLOAD_DIR/setalink-latest-arm32.apk"
ln -sf "../releases/$CHANNEL/$APK_NAME_UNIVERSAL" "$DOWNLOAD_DIR/setalink-latest-universal.apk"

# ── Generate version.json ─────────────────────────────────────────────────────
SHA=$(sha256sum "$APK_DEST" | awk '{print $1}')
SIZE=$(stat -c%s "$APK_DEST")
DATE=$(date +%Y-%m-%d)

# Merge into existing version.json instead of regenerating from scratch:
#  - the published channel gets version/versionCode + per-ABI URLs (arm64 /
#    arm32 / universal) so OTA serves each architecture the right package
#  - other channel entries are preserved verbatim
#  - admin-panel settings survive (forceUpdate, minSupported, rollout)
VJ_PATH="$VERSION_JSON" NEW_VERSION="$NEW_VERSION" NEW_CODE="$NEW_CODE" \
CHANNEL="$CHANNEL" DATE="$DATE" SHA="$SHA" SIZE="$SIZE" \
APK_NAME="$APK_NAME" APK_NAME_ARM32="$APK_NAME_ARM32" APK_NAME_UNIVERSAL="$APK_NAME_UNIVERSAL" \
python3 << 'PYEOF'
import json, os

p = os.environ['VJ_PATH']
try:
    with open(p) as f: d = json.load(f)
except Exception:
    d = {}

ch   = os.environ['CHANNEL']
ver  = os.environ['NEW_VERSION']
code = int(os.environ['NEW_CODE'])
base = f"https://setalink.no/releases/{ch}"
urls = {
    'apkUrl':          f"{base}/{os.environ['APK_NAME']}",
    'apkUrlArm32':     f"{base}/{os.environ['APK_NAME_ARM32']}",
    'apkUrlUniversal': f"{base}/{os.environ['APK_NAME_UNIVERSAL']}",
}

d.update({
    'version':        ver,
    'versionCode':    code,
    'releaseDate':    os.environ['DATE'],
    'rolloutChannel': ch,
    'apkUrlFallback': 'https://setalink.no/download/setalink-latest.apk',
    'checksum':       {'sha256': os.environ['SHA'], 'algorithm': 'sha256'},
    'size':           int(os.environ['SIZE']),
    'changelog':      [],            # old changelog described the old version
    **urls,
})
d.setdefault('minSupported', '0.9.7')
d.setdefault('forceUpdate', False)

d.setdefault('channels', {})
d['channels'][ch] = {'version': ver, 'versionCode': code, **urls}

with open(p, 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
PYEOF
echo "    version.json updated (channel=$CHANNEL, per-ABI URLs)"

# ── Prune old releases ──────────────────────────────────────────────────────
# This script only ever ADDED apk files, never removed old ones — hit "no
# space left on device" mid-CI-artifact-download twice on 2026-07-29 because
# of it (public/releases/beta/ alone had grown past 1.4G across every
# version back to 0.9.100, public/assets/ similarly). Keep the newest
# KEEP_RELEASES versions per directory; older ones are still recoverable
# from the matching git tag / CI artifact if ever needed, just not kept as
# live download files forever. Scoped to the channel just published (and
# public/assets/, which isn't channel-scoped) — deliberately does NOT touch
# owner-test-channel dirs like public/download/build101/, those are kept on
# purpose (see [[realink-owner-test-channels]]).
KEEP_RELEASES=5
prune_old_apks() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  local versions
  versions=$(find "$dir" -maxdepth 1 -name 'setalink-v*.apk' \
    ! -name '*-arm32.apk' ! -name '*-universal.apk' -printf '%T@ %f\n' \
    | sort -rn | awk '{print $2}' | sed -E 's/^setalink-v(.+)\.apk$/\1/')
  local keep=0
  while IFS= read -r v; do
    [[ -z "$v" ]] && continue
    keep=$((keep + 1))
    if (( keep > KEEP_RELEASES )); then
      rm -f "$dir/setalink-v${v}.apk" "$dir/setalink-v${v}-arm32.apk" "$dir/setalink-v${v}-universal.apk"
      echo "    pruned old release: v$v ($dir)"
    fi
  done <<< "$versions"
}
prune_old_apks "$CHANNEL_DIR"
prune_old_apks "$REPO_ROOT/public/assets"

# Ensure www-data (the PHP admin panel) can manage these paths. Must run
# LAST, after every read/write/prune above — doing this mid-script (as an
# earlier version did, right after the initial cp calls) meant the prune
# step's own `rm -f` a few lines later ran as ubuntu against files this
# same script had just re-owned to www-data one command earlier, failing
# with "Permission denied" and aborting before ever reaching the git
# commit/tag (hit exactly this on 2026-07-29 publishing v0.9.112).
sudo chown -R www-data:www-data "$CHANNEL_DIR" "$REPO_ROOT/public/assets" "$DOWNLOAD_DIR" 2>/dev/null || true

# ── Sync to the live serving directory ──────────────────────────────────────
# nginx's root for setalink.no is /var/www/setalink/public — a SEPARATE tree
# from this checkout ($REPO_ROOT) with no automatic sync between them.
# Everything above only ever touches this checkout, so without this step a
# "successful" release never actually goes live. Bit us twice: 2026-07-27
# (PHP files, fixed by hand) and 2026-07-29 (this exact release flow,
# also fixed by hand at the time — this step is that fix, made permanent).
# Best-effort: skipped with a warning, not a hard failure, on any box that
# isn't the setalink.no server itself.
LIVE_ROOT="/var/www/setalink"
if [[ -d "$LIVE_ROOT/public" ]]; then
  echo "==> Syncing release to live serving directory ($LIVE_ROOT)..."
  LIVE_PUBLIC="$LIVE_ROOT/public"
  LIVE_CHANNEL_DIR="$LIVE_PUBLIC/releases/$CHANNEL"

  sudo mkdir -p "$LIVE_CHANNEL_DIR" "$LIVE_PUBLIC/assets" "$LIVE_PUBLIC/download"

  sudo cp "$APK_DEST" "$CHANNEL_DIR/$APK_NAME_ARM32" "$CHANNEL_DIR/$APK_NAME_UNIVERSAL" "$LIVE_CHANNEL_DIR/"
  sudo ln -sf "$APK_NAME" "$LIVE_CHANNEL_DIR/setalink-latest.apk"
  sudo ln -sf "$APK_NAME_ARM32" "$LIVE_CHANNEL_DIR/setalink-latest-arm32.apk"
  sudo ln -sf "$APK_NAME_UNIVERSAL" "$LIVE_CHANNEL_DIR/setalink-latest-universal.apk"

  sudo cp "$REPO_ROOT/public/assets/$APK_NAME" "$LIVE_PUBLIC/assets/$APK_NAME"

  sudo cp "$VERSION_JSON" "$LIVE_PUBLIC/download/version.json"
  sudo ln -sf "../releases/$CHANNEL/$APK_NAME" "$LIVE_PUBLIC/download/setalink-latest.apk"
  sudo ln -sf "../releases/$CHANNEL/$APK_NAME_ARM32" "$LIVE_PUBLIC/download/setalink-latest-arm32.apk"
  sudo ln -sf "../releases/$CHANNEL/$APK_NAME_UNIVERSAL" "$LIVE_PUBLIC/download/setalink-latest-universal.apk"

  sudo chown -R www-data:www-data "$LIVE_CHANNEL_DIR" "$LIVE_PUBLIC/assets" "$LIVE_PUBLIC/download"

  # Verify immediately rather than trusting the copy — this is exactly the
  # kind of drift that went unnoticed for two days last time.
  LIVE_VERSION=$(curl -fsS "https://setalink.no/download/version.json" 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin).get("version",""))' 2>/dev/null || echo "")
  if [[ "$LIVE_VERSION" == "$NEW_VERSION" ]]; then
    echo "    Synced and verified live: version.json reports $LIVE_VERSION"
  else
    echo "    WARNING: live version.json reports '$LIVE_VERSION', expected '$NEW_VERSION' — check $LIVE_ROOT manually" >&2
  fi
else
  echo "==> Skipping live sync — $LIVE_ROOT not present on this box"
fi

# ── Git tag ───────────────────────────────────────────────────────────────────
cd "$REPO_ROOT"
git add mobile-app/package.json mobile-app/android/app/build.gradle mobile-app/src/utils/version.ts public/download/version.json .gitignore mobile-app/.gitignore
git commit -m "release: v$NEW_VERSION [$CHANNEL]

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
git tag -a "v$NEW_VERSION" -m "SetaLink v$NEW_VERSION [$CHANNEL]"
echo "    Committed and tagged v$NEW_VERSION"

echo ""
echo "✓ Release v$NEW_VERSION complete!"
echo "  APK:      $APK_DEST"
echo "  Symlink:  $CHANNEL_DIR/setalink-latest.apk → $APK_NAME"
echo "  Download: $DOWNLOAD_DIR/setalink-latest.apk"
echo "  version.json: $VERSION_JSON"
[[ -d "$LIVE_ROOT/public" ]] && echo "  Live:     synced to $LIVE_ROOT (see WARNING above if verification failed)"
echo ""
echo "  Push when ready:  git push && git push --tags"
